version: "3.8"
services:
  left4dead2:
    image: poormancontainer/l4d2simple:latest
    container_name: l4d2server
    network_mode: "host"
    volumes:
      - ${MODS}:/home/steam/left4dead2/left4dead2/addons
      - ${CONF}:/home/steam/left4dead2/left4dead2/cfg/server.cfg
    restart: unless-stopped
    command: "/home/steam/left4dead2/srcds_run -console -game left4dead2 +port 27005 +maxplayers 8 +exec server.cfg +map ${MAP} -nomaster"
